--- 
matrix: 
  include: 
    - 
      before_install: 
        - "cd fevertime_frontend"
      install: 
        - "yarn install"
      language: node_js
      node_js: 
        - "10"
      script: 
        - "./node_modules/.bin/eslint src"
        - "yarn test --coverage --watchAll=false"
    - 
      before_install: 
        - "cd fevertime_backend"
      install: 
        - "pip install pylint coverage django django-cors-headers"
      language: python
      python: 
        - "3.6"
      script:
        - "ls"
        - "python manage.py makemigrations user"
        - "python manage.py migrate user"
        - "python manage.py makemigrations"
        - "python manage.py migrate"
        - "coverage run --source='.' manage.py test"
        - "coverage report --fail-under=70"
        - "pylint **/*.py"
