# Generated by Django 2.2.5 on 2019-10-28 07:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fever_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=45)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('total_time', models.DurationField(default=datetime.timedelta(0))),
                ('fever_time', models.DurationField(default=datetime.timedelta(0))),
                ('fever_rate', models.FloatField(default=0)),
                ('fever_count', models.IntegerField(default=0)),
                ('click_end', models.CharField(default='N', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fever_history_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fever_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('fever_yn', models.CharField(default='N', max_length=1)),
                ('fever_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hid', to='fever.Fever_history')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fever_progress_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
